name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: https://github.com/jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
        with:
          github_token: ${{ secrets.ACTUAL_GITHUB_TOKEN }}

      - run: mise build --version ${{ github.event.release.tag_name }}

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: '!github.event.release.prerelease'
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/release/module.json, dist/release/daggerheart-quickstart.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
